# Generated by Django 3.0.3 on 2020-02-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200220_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=5)),
                ('eligibility', models.TextField()),
                ('duration', models.IntegerField(verbose_name='in years')),
                ('admission_fees', models.IntegerField()),
                ('tution_fees', models.IntegerField()),
                ('course_fees', models.IntegerField()),
                ('total_fees', models.IntegerField()),
            ],
        ),
    ]
