# Generated by Django 3.0.3 on 2020-02-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200226_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, default='none.jpg', null=True, upload_to='products'),
        ),
    ]
