# Generated by Django 3.0.3 on 2020-02-26 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='image',
        ),
    ]
